services:
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.51
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE}
      - SANDBOX_USER_ID=${SANDBOX_USER_ID}
      - SANDBOX_VOLUMES=${SANDBOX_VOLUMES}
      - SANDBOX_DOCKER_RUNTIME_KWARGS=${SANDBOX_DOCKER_RUNTIME_KWARGS}
      # - LOG_ALL_EVENTS=true
      # - DEBUG=true
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_INPUT_COST_PER_TOKEN=${LLM_INPUT_COST_PER_TOKEN}
      - LLM_OUTPUT_COST_PER_TOKEN=${LLM_OUTPUT_COST_PER_TOKEN}
      - ENABLE_BROWSER=true
    ports:
      - "3000:3000"
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - ${OPENHANDS_PATH}:/.openhands
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    pull_policy: always
